### PR TITLE
更正错别字

### PR DESCRIPTION
**Pull request by himao**

### CODE REVIEW

**Comment by feiskyer** [comment]
@himao thanks

**Comment by Justinlizhuo** [comment]
Dear feiskyer
	thank you for providing nice book k8s，i am a gitbook freshman，and have used your templete to write a new book。
	could you tell me the method to change "選擇一種語言”(choose one language) to another description？
	thank you very much


李卓Justin Li
顺送夏爽

**Comment by feiskyer** [comment]
@Justinlizhuo I'm afraid this is not easy to change. It's from gitbook's multi-language support feature.

See https://github.com/GitbookIO/theme-default/blob/master/_i18n/zh-tw.json for its origin.

**Comment by Justinlizhuo** [comment]
thank you very much.
which plug-in has triggered this feature, and is there any way to change this feature
Justin Li
Best wishes

**Comment by feiskyer** [comment]
https://github.com/feiskyer/kubernetes-handbook/blob/master/LANGS.md

**Pull request merged**
